export const departments = [
  {
    id: "ceo-ai",
    designation: "CEO AI",
    models: ["gpt-oss-120b"],
    primaryModel: "gpt-oss-120b",
    route: "command-center",
  },
  {
    id: "cto-ai",
    designation: "CTO AI",
    models: [
      "qwen3-coder-480b-a35b-instruct",
      "deepseek-v4-pro",
      "llama-3.3-nemotron-super-49b-v1.5",
    ],
    primaryModel: "qwen3-coder-480b-a35b-instruct",
    route: "ai-chat-workspace",
  },
  {
    id: "product-manager-ai",
    designation: "Product Manager AI",
    models: ["glm-5.1", "mistral-large-3-675b-instruct-2512", "step-3.5-flash"],
    primaryModel: "glm-5.1",
    route: "organization-dashboard",
  },
  {
    id: "research-ai",
    designation: "Research AI",
    models: ["gemma-4-31b-it", "seed-oss-36b-instruct", "llama-3.3-70b-instruct"],
    primaryModel: "gemma-4-31b-it",
    route: "knowledge-base",
  },
  {
    id: "market-intelligence-ai",
    designation: "Market Intelligence AI",
    models: ["deepseek-v4-flash", "qwen3.5-122b-a10b", "glm-5.1"],
    primaryModel: "deepseek-v4-flash",
    route: "fintech-dashboard",
  },
  {
    id: "voice-ai",
    designation: "Voice AI",
    models: [
      "whisper-large-v3",
      "nemotron-voicechat",
      "magpie-tts-multilingual",
      "magpie-tts-zeroshot",
    ],
    primaryModel: "whisper-large-v3",
    route: "voice-console",
  },
  {
    id: "document-ai",
    designation: "Document AI",
    models: ["nemotron-ocr-v1", "paddleocr", "nemotron-parse", "nemotron-table-structure-v1"],
    primaryModel: "nemotron-ocr-v1",
    route: "ocr-workspace",
  },
  {
    id: "memory-ai",
    designation: "Memory AI",
    models: ["bge-m3", "nv-embed-v1", "llama-nemotron-embed-1b-v2"],
    primaryModel: "bge-m3",
    route: "knowledge-base",
  },
  {
    id: "security-ai",
    designation: "Security AI",
    models: [
      "llama-guard-4-12b",
      "nemoguard-jailbreak-detect",
      "gliner-pii",
      "nemotron-content-safety-reasoning-4b",
    ],
    primaryModel: "llama-guard-4-12b",
    route: "security-center",
  },
  {
    id: "creative-ai",
    designation: "Creative AI",
    models: ["FLUX.1-dev", "FLUX.1-schnell", "qwen-image", "stable-diffusion-3.5-large"],
    primaryModel: "FLUX.1-dev",
    route: "ai-studio",
  },
  {
    id: "media-ai",
    designation: "Media AI",
    models: ["LipSync", "AI for Media Relighting", "synthetic-video-detector", "studiovoice"],
    primaryModel: "LipSync",
    route: "media-studio",
  },
  {
    id: "3d-ai",
    designation: "3D AI",
    models: ["TRELLIS", "usdcode", "usdvalidate", "vista-3d", "cosmos-predict1-5b"],
    primaryModel: "TRELLIS",
    route: "3d-studio",
  },
];

export const providers = [
  "OpenAI",
  "NVIDIA",
  "Qwen",
  "DeepSeek",
  "Google",
  "Mistral",
  "Meta",
  "Stability AI",
  "Black Forest Labs",
  "Microsoft",
  "Moonshot AI",
  "GLM",
  "Others",
];
